// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzlSoQSI3qMqE03-b8B0QwQShVE51bSE',
    appId: '1:927238346895:web:06a93bc505192d3487f8fa',
    messagingSenderId: '927238346895',
    projectId: 'mobilitycli',
    authDomain: 'mobilitycli.firebaseapp.com',
    storageBucket: 'mobilitycli.appspot.com',
    measurementId: 'G-8XB9FYXF86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesWBxMeLk4ZAub8fpQAVnsyqc3Emhj04',
    appId: '1:927238346895:android:77d21140e2303b9187f8fa',
    messagingSenderId: '927238346895',
    projectId: 'mobilitycli',
    storageBucket: 'mobilitycli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtOYPndZFREUxlcy1Wd4t0iHgmpMdV6Y',
    appId: '1:927238346895:ios:c8ed011cfd64849087f8fa',
    messagingSenderId: '927238346895',
    projectId: 'mobilitycli',
    storageBucket: 'mobilitycli.appspot.com',
    iosBundleId: 'com.example.mobilityLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtOYPndZFREUxlcy1Wd4t0iHgmpMdV6Y',
    appId: '1:927238346895:ios:c8ed011cfd64849087f8fa',
    messagingSenderId: '927238346895',
    projectId: 'mobilitycli',
    storageBucket: 'mobilitycli.appspot.com',
    iosBundleId: 'com.example.mobilityLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfzlSoQSI3qMqE03-b8B0QwQShVE51bSE',
    appId: '1:927238346895:web:70619d3a1eb23fe087f8fa',
    messagingSenderId: '927238346895',
    projectId: 'mobilitycli',
    authDomain: 'mobilitycli.firebaseapp.com',
    storageBucket: 'mobilitycli.appspot.com',
    measurementId: 'G-JNDS7N8ZP3',
  );
}
